spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elevate_dev
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
jwt:
  secret: b5i2nc9E4Awb0cT3xYvF3xKk0wVjaXcqcIUe25Rk6ZE=   # 256-bit base64
